{% set data = load_setup_py_data() %}

package:
  name: manta
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/ramellose/manta

requirements:
  host:
    - python >=3.5
    - setuptools
  run:
    - python >=3.5
    - numpy >=1.15.0
    - scipy >=1.4.1
    - networkx >=2.2
    - pandas >=1.1.5
    - scikit-learn>=0.18

about:
  home: https://github.com/ramellose/manta
  license: Apache 2.0
  license_file: LICENSE
  summary: "Clustering microbial associations"