{% set version = "v1.1.0" %}

package:
  name: manta
  version: "{{ version }}"

source:
  url: https://github.com/ramellose/manta/archive/v1.1.0.tar.gz
  sha256: c73cd9eaf5e90530add0260b15da243f62fe146b623e1f1d5e3c15bb29cfea6e

build:
  noarch: python
  number: 0
  script: python -m pip install .
  entry_points:
    - anuran = anuran.main:main

requirements:
  host:
    - python >=3.5
    - setuptools
    - pbr
  run:
    - python >=3.5
    - numpy >=1.15.0
    - scipy >=1.4.1
    - networkx >=2.2
    - pandas >=1.1.5
    - scikit-learn>=0.18
    - pbr

about:
  home: https://github.com/ramellose/manta
  license: Apache 2.0
  license_file: LICENSE
  summary: "Clustering microbial associations"