{% set version = "1.1.0" %}

package:
  name: manta
  version: "{{ version }}"

source:
  url: https://github.com/ramellose/manta

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - manta = manta.main:main

requirements:
  host:
    - python >=3.5
    - setuptools
    - pbr
  run:
    - python >=3.5
    - numpy >=1.15.0
    - scipy >=1.4.1
    - networkx >=2.2
    - pandas >=1.1.5
    - scikit-learn>=0.18
    - pbr

about:
  home: https://github.com/ramellose/manta
  license: Apache 2.0
  license_file: LICENSE
  summary: "Clustering microbial associations"